### ISSUE TITLE
BBCodes in ACP

### ISSUE THREAD

**Issue by jan-2017** [marttiphpbb/phpbb-ext-topictemplate#1]
Is it possible to include the BBCodes commands displayed above the text editor in acp?

**Comment by marttiphpbb** [comment]
You can use all the BBCodes that are enabled on your board. The BBCode Buttons are not included in order to keep things simple. (This also the case with the "Forum Rules" on the same page in ACP). 
You could compose your "Topic Template" in the normal posting editor and see the preview and then copy paste to the "Topic Template" text field in the Forum ACP.
